name: frame_forge
description: "The BDUI Flutter project with advanced layout editing capabilities."
version: 0.0.1
homepage: http://itjn.ru
repository: https://github.com/itjn-ru/layout_editor
environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  web: ^1.1.1
  uuid: ^4.4.0
  xml: ^6.5.0
  keymap: ^0.0.92
  file_picker: ^9.0.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  
flutter:
